"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import sys

def osx():
    return sys.platform == 'darwin'

if osx():
    from setuptools import setup

    APP = ['rengabit.py']
    DATA_FILES = []
    OPTIONS = {'argv_emulation': True}

    setup(
    app=APP,
        data_files=DATA_FILES,
        options={'py2app': OPTIONS},
        setup_requires=['py2app'],
    )

else:
    from distutils.core import setup
    import py2exe

    setup(console=['rengabit.py'])
